### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by techtonik** [python-modernize/python-modernize#125]
It's been a year since the last modernize release - https://pypi.python.org/pypi/modernize

I need `python -m modernize` from it.

**Comment by takluyver** [comment]
I see no obstacle to making a release. @daira , @brettcannon , are you aware of anything we should get in before cutting 0.5?

**Comment by techtonik** [comment]
Not critical, but I'd also include #121 for Windows to avoid rewriting linefeeds back to \n manually.

**Comment by takluyver** [comment]
As the nicest way to fix that would be to change 2to3, I suspect it's not worth it for 0.5. But if you want to get a pull request together, go for it.

**Comment by techtonik** [comment]
@takluyver maybe subclassing 2to3 will be enough, but I can't dwell deep enough for now to ensure.

**Comment by techtonik** [comment]
@takluyver just release it as-is. Looks like there is no time to work on #121.

**Comment by takluyver** [comment]
Done.

**Comment by techtonik** [comment]
@takluyver Thanks!
