### ISSUE TITLE
new point release

### ISSUE THREAD

**Issue by nickpell** [python-modernize/python-modernize#158]
I would like to see a 0.6.0 or 0.5.1 version that incorporates recent updates.

**Comment by takluyver** [comment]
Happy to do so. I'd probably call it 0.6, or maybe even 1.0. @daira @brettcannon any preference?

Looking at the commit log, hat tip to @rowillia, who has made most of the changes to the code since 0.5.

**Comment by brettcannon** [comment]
No preference from me.

**Comment by takluyver** [comment]
Modernize 0.6 is out, thanks for the reminder.
