### ISSUE TITLE
Cannot exclude the 'import' fixer in 0.6

### ISSUE THREAD

**Issue by MartinFalatic** [python-modernize/python-modernize#163]
Whether I use `--nofix=import` or `-x import`, I cannot exclude the `import` fixer from `python-modernize`.

This exclusion works as expected (with either syntax) with `2to3`.

**Comment by MartinFalatic** [comment]
Actually, this applies to *any* of the fixers. I'm working on a fix for this that allows both short names (as listed in the documentation) as well as the long-form names understood only by python-modernize currently.

**Comment by takluyver** [comment]
Great! That will also fix #27.
