### ISSUE TITLE
Allow external fixers on command-line tool

### ISSUE THREAD

**Issue by shaib** [python-modernize/python-modernize#166]
The section on Fixers at https://python-modernize.readthedocs.io/en/latest/fixers.html ends with a note about "implementing your own fixers"; however, `libmodernize.main.main` collects the available fixers from `libmodernize.fixes` and `lib2to3.fixes`, and if a fixer not found in these two places is specified on the command line, errors out with `"Error: fix '{}' was not found"`.

It would be more helpful to try to import and load the fixer in such cases.  if a fix explicitly mentioned was not found, an attempt should be made to import and load it.

I note that modernize has inherited this behavior from 2to3 -- but the only reason I see for it is to make sure that `-l` indeed provides a full list; a problem which could be addressed by changing that option's help-string, IMO.

**Comment by takluyver** [comment]
Makes sense, PRs welcome :-)

**Comment by shaib** [comment]
Just for the record, #167
