### ISSUE TITLE
lib2to3 is deprecated, depend on fissix instead?

### ISSUE THREAD

**Issue by graingert** [python-modernize/python-modernize#202]
https://github.com/python/cpython/commit/503de7149d03bdcc671dcbbb5b64f761bb192b4d
https://pypi.org/project/fissix/

**Comment by jayvdb** [comment]
Cross linking to PR https://github.com/python-modernize/python-modernize/pull/203 which does this.

**Comment by graingert** [comment]
@takluyver thanks so much for the review! Can we get a release of this please?

**Comment by graingert** [comment]
@takluyver do you want me to cut a release for this? is there a process to follow for that?

**Comment by takluyver** [comment]
Feel free to. As far as I remember, it's just [bump the version number](https://github.com/python-modernize/python-modernize/commit/5650894e684250b8dd7a7d552adeea98eb8663ba), upload to PyPI, and tag it in git.

**Comment by graingert** [comment]
released as rc1 as I was too chicken for a full release: https://pypi.org/project/modernize/0.8rc1/
